# Project information
site_name: Introduction to Computer Systems Spring 2025
site_url: https://xjtu-ics.github.io/
site_author: XJTU-ICS TEAM
site_description: >-
  XJTU-ICS Webpage
# Repository
repo_name: xjtu-ics/xjtu-ics.github.io
repo_url: https://github.com/xjtu-ics/xjtu-ics.github.io
# Copyright
copyright: Copyright &copy; 2025 XJTU ICS-TEAM
# Configuration
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.select
  palette:
    primary: black
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
# Plugins
plugins:
  - search
  - tags
  - table-reader

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  version:
    # provider: mike
    alias: true
extra_css:
  - stylesheets/custom.css
# Page tree
nav:
  - Overview: index.md
  - Calendar: calendar/index.md
  - Labs:
    - Tutorial and Environmental Preparation: labs/lab0.md
    # - Data Lab: labs/lab1.md
    # - Bomb Lab: labs/lab2.md
    # - Attack Lab: labs/lab3.md
    # - Cache Lab: labs/lab4.md
    # - Optimization Lab: labs/lab5.md
    # - Linker Lab: labs/lab6.md
  - Staff: staff/index.md
  - Policies: policies/index.md
  - Resources:
    - Quick Reference: resources/quickreference.md
    - ICS-Server: resources/ICS-Server.md
    - VSCode Remote-SSH Setting: resources/VScodeRemote-SSH.md
    - Linux Installation: resources/LinuxInstallation.md
  - FAQ: FAQ/index.md
